# Generated by Django 6.0.6 on 2026-06-22 00:10

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('eyebrow', models.CharField(default='Reach Out', max_length=100)),
                ('heading', models.CharField(default="Let's Build Together", max_length=200)),
                ('intro', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Contact Page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='GalleryPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('eyebrow', models.CharField(default='Our Moments', max_length=100)),
                ('heading', models.CharField(default='Gallery', max_length=200)),
                ('intro', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Gallery Page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='GalleryProgramPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Gallery Program',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('eyebrow', models.CharField(default='Who We Are', max_length=100)),
                ('heading', models.CharField(default='Rooted in Purpose, Driven by People', max_length=200)),
                ('intro', models.TextField(blank=True)),
                ('mission', models.TextField(blank=True)),
                ('vision', models.TextField(blank=True)),
                ('values', models.TextField(blank=True)),
                ('approach', models.TextField(blank=True)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'About Page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('hero_eyebrow', models.CharField(default='Empowering Communities, Transforming Lives', max_length=100)),
                ('hero_title', models.CharField(default='Building a Stronger Community Together', max_length=200)),
                ('hero_subtitle', models.TextField(blank=True)),
                ('stat_lives', models.CharField(default='5,000+', max_length=20)),
                ('stat_communities', models.CharField(default='12+', max_length=20)),
                ('stat_pillars', models.CharField(default='3', max_length=20)),
                ('stat_volunteers', models.CharField(default='100+', max_length=20)),
                ('hero_logo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Home Page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ProgramMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('video', models.FileField(blank=True, null=True, upload_to='gallery/videos/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='home.galleryprogrampage')),
            ],
            options={
                'verbose_name': 'Media',
            },
        ),
    ]
