# Generated by Django 6.0.6 on 2026-06-22 11:02

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='stat_communities',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='stat_lives',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='stat_pillars',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='stat_volunteers',
        ),
        migrations.CreateModel(
            name='HomePillar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('icon', models.CharField(default='🌱', help_text='Paste an emoji', max_length=10)),
                ('heading', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='pillars', to='home.homepage')),
            ],
            options={
                'verbose_name': 'Pillar',
            },
        ),
    ]
